os:
  - linux

language: python
python:
  - "3.6"

install:
 - pip install coveralls
 - pip install -r requirements.txt


script:
  - coverage run  --source app  -m unittest discover tests
#  - python -m unittest discover tests

after_success:
    coveralls